name: zefyr
description: Clean, minimalistic and collaboration-ready rich text editor for Flutter.
version: 0.6.0
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
homepage: https://github.com/memspace/zefyr

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.6
  url_launcher: 
    git:
      url: https://github.com/flutter/plugins.git
      path: packages/url_launcher
  image_picker: ^0.6.1
  quill_delta: ^1.0.0-dev.1.0
  notus: ^0.1.0
  meta: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
